"""UNC Chapel Hill seed data for all resource types."""

COURSES = [
    {
        "id": "comp110", "code": "COMP 110", "title": "Introduction to Programming and Data Science",
        "department": "Computer Science", "credits": 3, "instructor": "Kris Jordan",
        "description": "Introduction to programming for data science and software engineering using Python.",
        "seats_available": 12, "total_seats": 120, "schedule": "MWF 10:10-11:00",
        "location": "Sitterson Hall 014", "tags": ["python", "beginner", "data science"],
    },
    {
        "id": "comp210", "code": "COMP 210", "title": "Data Structures and Analysis",
        "department": "Computer Science", "credits": 3, "instructor": "John Majikes",
        "description": "Classic data structures: lists, trees, graphs, hash tables, and algorithm analysis.",
        "seats_available": 5, "total_seats": 80, "schedule": "TTh 11:00-12:15",
        "location": "Sitterson Hall 011", "tags": ["java", "algorithms", "data structures"],
    },
    {
        "id": "comp311", "code": "COMP 311", "title": "Computer Organization",
        "department": "Computer Science", "credits": 3, "instructor": "Brent Munsell",
        "description": "Instruction-set architecture, assembly language, digital logic, and memory hierarchy.",
        "seats_available": 0, "total_seats": 60, "schedule": "MWF 11:15-12:05",
        "location": "Sitterson Hall 014", "tags": ["systems", "assembly", "architecture"],
    },
    {
        "id": "comp411", "code": "COMP 411", "title": "Computer Organization",
        "department": "Computer Science", "credits": 3, "instructor": "Don Smith",
        "description": "Advanced computer organization including pipelining and cache design.",
        "seats_available": 8, "total_seats": 50, "schedule": "TTh 9:30-10:45",
        "location": "Sitterson Hall 011", "tags": ["systems", "hardware", "advanced"],
    },
    {
        "id": "comp521", "code": "COMP 521", "title": "Files and Databases",
        "department": "Computer Science", "credits": 3, "instructor": "Raymond Duba",
        "description": "Relational databases, SQL, indexing, query optimization, and transaction processing.",
        "seats_available": 15, "total_seats": 45, "schedule": "TTh 2:00-3:15",
        "location": "Sitterson Hall 228", "tags": ["databases", "sql", "systems"],
    },
    {
        "id": "comp590ds", "code": "COMP 590 DS", "title": "Distributed Systems",
        "department": "Computer Science", "credits": 3, "instructor": "Jasleen Kaur",
        "description": "Consistency, replication, consensus protocols, and distributed storage systems.",
        "seats_available": 3, "total_seats": 30, "schedule": "MWF 1:25-2:15",
        "location": "Sitterson Hall 115", "tags": ["distributed", "advanced", "networking"],
    },
    {
        "id": "biol101", "code": "BIOL 101", "title": "Introductory Biology",
        "department": "Biology", "credits": 3, "instructor": "Amy Maddox",
        "description": "Molecular and cellular biology, genetics, and evolution fundamentals.",
        "seats_available": 30, "total_seats": 200, "schedule": "MWF 9:05-9:55",
        "location": "Genome Sciences Building G100", "tags": ["biology", "science", "intro"],
    },
    {
        "id": "chem101", "code": "CHEM 101", "title": "General Chemistry",
        "department": "Chemistry", "credits": 3, "instructor": "Cynthia Schauer",
        "description": "Stoichiometry, thermodynamics, kinetics, and equilibrium in chemical systems.",
        "seats_available": 20, "total_seats": 160, "schedule": "MWF 8:00-8:50",
        "location": "Venable Hall 100", "tags": ["chemistry", "science", "intro"],
    },
    {
        "id": "engl105", "code": "ENGL 105", "title": "Writing in College",
        "department": "English", "credits": 3, "instructor": "Staff",
        "description": "Writing workshop focusing on argumentation, research, and academic communication.",
        "seats_available": 6, "total_seats": 20, "schedule": "TTh 11:00-12:15",
        "location": "Greenlaw Hall 201", "tags": ["writing", "english", "required"],
    },
    {
        "id": "math231", "code": "MATH 231", "title": "Calculus of Functions of One Variable I",
        "department": "Mathematics", "credits": 4, "instructor": "Jeremy Marzuola",
        "description": "Limits, derivatives, integrals, and the fundamental theorem of calculus.",
        "seats_available": 18, "total_seats": 100, "schedule": "MWF 10:10-11:00 + recitation",
        "location": "Phillips Hall 215", "tags": ["math", "calculus", "required"],
    },
    {
        "id": "stat101", "code": "STOR 101", "title": "Introduction to Data Analysis",
        "department": "Statistics and Operations Research", "credits": 3, "instructor": "Jan Hannig",
        "description": "Descriptive statistics, probability, confidence intervals, and hypothesis testing.",
        "seats_available": 25, "total_seats": 120, "schedule": "TTh 9:30-10:45",
        "location": "Hanes Hall 120", "tags": ["statistics", "data", "intro"],
    },
    {
        "id": "poli100", "code": "POLI 100", "title": "Introduction to American Government",
        "department": "Political Science", "credits": 3, "instructor": "Frank Baumgartner",
        "description": "Constitutional design, political parties, elections, and policy-making in the U.S.",
        "seats_available": 40, "total_seats": 200, "schedule": "MWF 12:20-1:10",
        "location": "Hamilton Hall 100", "tags": ["political science", "government", "intro"],
    },
]

CLUBS = [
    {
        "id": "unc-sg", "name": "UNC Student Government",
        "category": "Governance", "description": "The official student government representing all UNC undergraduates.",
        "meeting_schedule": "Tuesdays 7:00 PM", "location": "Student Union 3400",
        "president": "Ellie Parker", "email": "unc.studentgov@unc.edu",
        "member_count": 250, "founded": 1932, "tags": ["leadership", "advocacy", "governance"],
    },
    {
        "id": "cs-club", "name": "Carolina Hackers (CS Club)",
        "category": "Academic / Tech", "description": "Weekly coding meetups, hackathons, and industry speaker events.",
        "meeting_schedule": "Thursdays 6:30 PM", "location": "Sitterson Hall 11",
        "president": "Marcus Chen", "email": "carolinahackers@unc.edu",
        "member_count": 320, "founded": 2004, "tags": ["coding", "hackathon", "tech"],
    },
    {
        "id": "swe-unc", "name": "Society of Women Engineers – UNC",
        "category": "Academic / Professional", "description": "Empowering women pursuing engineering and CS degrees.",
        "meeting_schedule": "Wednesdays 5:00 PM", "location": "Phillips Hall 332",
        "president": "Anika Sharma", "email": "swe@unc.edu",
        "member_count": 180, "founded": 1998, "tags": ["women in tech", "engineering", "professional"],
    },
    {
        "id": "bsm", "name": "Black Student Movement",
        "category": "Cultural", "description": "The oldest Black student organization at UNC, advocating for racial equity.",
        "meeting_schedule": "Mondays 7:00 PM", "location": "Stone Center",
        "president": "Jordan Williams", "email": "bsm@unc.edu",
        "member_count": 400, "founded": 1967, "tags": ["cultural", "advocacy", "community"],
    },
    {
        "id": "cuab", "name": "Carolina Union Activities Board",
        "category": "Programming", "description": "Plans large-scale campus events including concerts and Late Night.",
        "meeting_schedule": "Sundays 6:00 PM", "location": "Student Union 3119",
        "president": "Taylor Brooks", "email": "cuab@unc.edu",
        "member_count": 150, "founded": 1972, "tags": ["events", "programming", "entertainment"],
    },
    {
        "id": "asa-unc", "name": "Asian Students Association",
        "category": "Cultural", "description": "Celebrating Asian heritage through cultural events and community support.",
        "meeting_schedule": "Fridays 5:30 PM", "location": "Greenlaw Hall 200",
        "president": "Lily Nguyen", "email": "asa@unc.edu",
        "member_count": 270, "founded": 1985, "tags": ["cultural", "community", "diversity"],
    },
    {
        "id": "debate", "name": "Carolina Debate",
        "category": "Academic", "description": "Nationally ranked competitive debate team in policy and parliamentary formats.",
        "meeting_schedule": "MWF 4:00 PM", "location": "Caldwell Hall 105",
        "president": "Sam Torres", "email": "carolinadebate@unc.edu",
        "member_count": 60, "founded": 1924, "tags": ["debate", "public speaking", "competitive"],
    },
    {
        "id": "premed", "name": "Pre-Medical Society",
        "category": "Pre-Professional", "description": "MCAT prep, shadowing opportunities, and medical school admissions guidance.",
        "meeting_schedule": "Tuesdays 6:00 PM", "location": "Genome Sciences Building 2204",
        "president": "Rachel Kim", "email": "premed@unc.edu",
        "member_count": 500, "founded": 1975, "tags": ["pre-med", "healthcare", "professional"],
    },
    {
        "id": "cea", "name": "Carolina Environmental Action",
        "category": "Advocacy", "description": "Student activism on climate change, sustainability, and environmental justice.",
        "meeting_schedule": "Thursdays 7:00 PM", "location": "Environment Hall 101",
        "president": "Maya Rodriguez", "email": "cea@unc.edu",
        "member_count": 130, "founded": 1968, "tags": ["environment", "sustainability", "activism"],
    },
    {
        "id": "chess", "name": "UNC Chess Club",
        "category": "Recreation", "description": "Open to all skill levels; participates in collegiate chess tournaments.",
        "meeting_schedule": "Saturdays 2:00 PM", "location": "Davis Library Room 240",
        "president": "Ivan Petrov", "email": "uncchess@unc.edu",
        "member_count": 55, "founded": 2001, "tags": ["chess", "games", "strategy"],
    },
]

RESEARCH = [
    {
        "id": "lineberger", "title": "Novel Immunotherapy Targets in Triple-Negative Breast Cancer",
        "department": "Medicine / Pharmacology", "pi": "Dr. Lisa Carey",
        "description": "Identifying actionable immune checkpoints in TNBC using single-cell RNA sequencing and CRISPR screens.",
        "funding_source": "NIH/NCI", "funding_amount": "$2.4M", "status": "active",
        "lab": "UNC Lineberger Comprehensive Cancer Center",
        "tags": ["cancer", "immunotherapy", "genomics"],
    },
    {
        "id": "renci-cloud", "title": "Distributed Cloud Infrastructure for Scientific Workflows",
        "department": "Computer Science / RENCI", "pi": "Dr. Paul Ruth",
        "description": "Building open-source software-defined networking and cloud testbeds for big-data science.",
        "funding_source": "NSF", "funding_amount": "$1.8M", "status": "active",
        "lab": "Renaissance Computing Institute (RENCI)",
        "tags": ["cloud", "networking", "distributed systems"],
    },
    {
        "id": "igh-malaria", "title": "Malaria Vaccine Efficacy in Sub-Saharan Africa",
        "department": "Epidemiology", "pi": "Dr. Steven Meshnick",
        "description": "Phase III clinical trials evaluating RTS,S malaria vaccine efficacy in children under 5 in Malawi.",
        "funding_source": "Bill & Melinda Gates Foundation", "funding_amount": "$5.1M", "status": "active",
        "lab": "UNC Institute for Global Health",
        "tags": ["global health", "malaria", "vaccine", "Africa"],
    },
    {
        "id": "cpc-aging", "title": "Longitudinal Aging and Health Equity Study",
        "department": "Public Health", "pi": "Dr. Kathleen Mullan Harris",
        "description": "25-year cohort study examining social determinants of aging using Add Health data.",
        "funding_source": "NIH/NIA", "funding_amount": "$3.7M", "status": "active",
        "lab": "Carolina Population Center",
        "tags": ["aging", "public health", "equity", "longitudinal"],
    },
    {
        "id": "nlp-lab", "title": "Low-Resource Neural Machine Translation",
        "department": "Computer Science", "pi": "Dr. Mohit Bansal",
        "description": "Cross-lingual transfer learning for endangered and low-resource languages using multilingual LLMs.",
        "funding_source": "DARPA / NSF", "funding_amount": "$900K", "status": "active",
        "lab": "MURGe-Lab (Multimodal Understanding and Reasoning for Grounding)",
        "tags": ["NLP", "machine learning", "linguistics"],
    },
    {
        "id": "robotics-lab", "title": "Adaptive Robot Manipulation in Unstructured Environments",
        "department": "Computer Science", "pi": "Dr. Ron Alterovitz",
        "description": "Motion planning algorithms enabling robotic surgical tools to navigate soft tissue safely.",
        "funding_source": "NIH/NCI", "funding_amount": "$1.2M", "status": "recruiting",
        "lab": "Computational Robotics Research Group",
        "tags": ["robotics", "surgery", "motion planning", "AI"],
    },
    {
        "id": "hussman-misinformation", "title": "Political Misinformation Spread on Social Media",
        "department": "Journalism / Political Science", "pi": "Dr. Daniel Kreiss",
        "description": "Mixed-methods study on how partisan media ecosystems amplify false political narratives.",
        "funding_source": "Knight Foundation", "funding_amount": "$600K", "status": "active",
        "lab": "UNC Hussman School of Journalism and Media",
        "tags": ["misinformation", "social media", "journalism", "politics"],
    },
    {
        "id": "env-microplastics", "title": "Microplastic Contamination in Carolina Waterways",
        "department": "Environmental Sciences & Engineering", "pi": "Dr. Francois Perreault",
        "description": "Field sampling and lab analysis of microplastic concentrations in Eno River tributaries.",
        "funding_source": "EPA / NC DEQ", "funding_amount": "$450K", "status": "recruiting",
        "lab": "Gillings School of Global Public Health – ESE",
        "tags": ["environment", "microplastics", "water quality"],
    },
]

EVENTS = [
    {
        "id": "ldoc-2024", "title": "LDOC Fest (Last Day of Classes)",
        "organizer": "Carolina Union Activities Board", "date": "2025-04-25",
        "time": "12:00 PM – 5:00 PM", "location": "Polk Place",
        "description": "Annual outdoor music festival celebrating the last day of spring classes with live performances and food trucks.",
        "category": "Festival", "capacity": 5000, "rsvp_required": False,
        "tags": ["music", "outdoor", "tradition", "annual"],
    },
    {
        "id": "homecoming-2024", "title": "UNC Homecoming Weekend",
        "organizer": "UNC Student Government", "date": "2025-10-18",
        "time": "All Day", "location": "Kenan Stadium & Campus",
        "description": "Parade, pep rally, alumni reunions, and football game vs. rival. One of UNC's signature traditions.",
        "category": "Tradition", "capacity": 20000, "rsvp_required": False,
        "tags": ["homecoming", "football", "tradition", "alumni"],
    },
    {
        "id": "career-fair-spring", "title": "Spring Career & Internship Fair",
        "organizer": "University Career Services", "date": "2025-02-19",
        "time": "11:00 AM – 3:00 PM", "location": "Fetzer Gym",
        "description": "Over 150 employers recruiting for full-time roles and internships in tech, finance, healthcare, and more.",
        "category": "Career", "capacity": 2000, "rsvp_required": True,
        "tags": ["career", "jobs", "internship", "networking"],
    },
    {
        "id": "science-expo", "title": "UNC Science Expo",
        "organizer": "Office of Undergraduate Research", "date": "2025-03-08",
        "time": "10:00 AM – 2:00 PM", "location": "Genome Sciences Atrium",
        "description": "Undergraduate students present research posters across biology, chemistry, physics, and environmental science.",
        "category": "Academic", "capacity": 800, "rsvp_required": False,
        "tags": ["research", "science", "undergraduate", "posters"],
    },
    {
        "id": "cultural-fest", "title": "International Cultural Festival",
        "organizer": "Office of International Students & Scholars", "date": "2025-04-05",
        "time": "1:00 PM – 6:00 PM", "location": "The Pit",
        "description": "Celebrating 100+ nationalities on campus with traditional food, music, dance performances, and cultural booths.",
        "category": "Cultural", "capacity": 3000, "rsvp_required": False,
        "tags": ["culture", "international", "diversity", "food"],
    },
    {
        "id": "hackathon-2025", "title": "HackNC 2025",
        "organizer": "Carolina Hackers", "date": "2025-10-04",
        "time": "6:00 PM (24-hour hackathon)", "location": "Sitterson & Brooks Buildings",
        "description": "UNC's annual 24-hour hackathon open to all skill levels with $10K in prizes and mentors from Google, Microsoft, and Cisco.",
        "category": "Tech", "capacity": 500, "rsvp_required": True,
        "tags": ["hackathon", "coding", "prizes", "tech"],
    },
    {
        "id": "planetarium-show", "title": "Morehead Planetarium: Cosmic Wonders",
        "organizer": "Morehead Planetarium and Science Center", "date": "2025-09-20",
        "time": "7:30 PM", "location": "Morehead Planetarium",
        "description": "Immersive 360° dome show exploring black holes, neutron stars, and the evolution of the universe.",
        "category": "Educational", "capacity": 120, "rsvp_required": True,
        "tags": ["astronomy", "science", "planetarium", "family"],
    },
    {
        "id": "meditation-week", "title": "Mindfulness & Wellness Week",
        "organizer": "Campus Health & Student Wellness", "date": "2025-10-14",
        "time": "Various times", "location": "SASB North & The Pit",
        "description": "Week-long series with guided meditations, stress-relief workshops, therapy dog visits, and yoga classes.",
        "category": "Wellness", "capacity": None, "rsvp_required": False,
        "tags": ["wellness", "mental health", "mindfulness", "stress"],
    },
]

DINING = [
    {
        "id": "lenoir", "name": "Lenoir Hall Dining",
        "type": "dining_hall", "location": "Lenoir Hall, Central Campus",
        "hours": "Mon–Fri 7 AM–9 PM | Sat–Sun 8 AM–8 PM",
        "menu_highlights": ["All-you-care-to-eat", "Vegan station", "Allergen-free zone", "Wood-fired pizza"],
        "meal_plan_accepted": True,
        "cuisine_types": ["American", "Vegan", "Italian", "Asian Fusion"],
        "rating": 4.2, "tags": ["all-you-eat", "meal-plan", "large", "vegan-friendly"],
    },
    {
        "id": "chase", "name": "Chase Dining Hall",
        "type": "dining_hall", "location": "Chase Residence Hall, South Campus",
        "hours": "Mon–Fri 7:30 AM–8:30 PM | Sat–Sun 9 AM–7 PM",
        "menu_highlights": ["Rotating global cuisine", "Halal station", "Salad bar", "Custom omelets"],
        "meal_plan_accepted": True,
        "cuisine_types": ["Mediterranean", "Mexican", "Indian", "Halal"],
        "rating": 4.5, "tags": ["meal-plan", "halal", "south-campus"],
    },
    {
        "id": "rams-head", "name": "Ram's Head Dining",
        "type": "dining_hall", "location": "Ram's Head Residence Area, South Campus",
        "hours": "Mon–Sun 7 AM–10 PM",
        "menu_highlights": ["Late-night dining", "Carolina BBQ station", "Dessert bar", "Smoothie bar"],
        "meal_plan_accepted": True,
        "cuisine_types": ["Southern BBQ", "American", "Smoothies", "Desserts"],
        "rating": 4.3, "tags": ["late-night", "meal-plan", "south-campus", "desserts"],
    },
    {
        "id": "top-of-lenoir", "name": "Top of Lenoir",
        "type": "cafe", "location": "Lenoir Hall, 2nd Floor",
        "hours": "Mon–Fri 7:30 AM–3 PM",
        "menu_highlights": ["Artisan coffee", "Fresh pastries", "Breakfast burritos", "Paninis"],
        "meal_plan_accepted": False,
        "cuisine_types": ["Coffee", "Bakery", "Sandwiches"],
        "rating": 4.6, "tags": ["coffee", "breakfast", "quick", "cafe"],
    },
    {
        "id": "alpine-bagel", "name": "Alpine Bagel Cafe",
        "type": "cafe", "location": "Undergraduate Library (Davis Library Lower Level)",
        "hours": "Mon–Fri 8 AM–4 PM",
        "menu_highlights": ["NY-style bagels", "Lox & cream cheese", "Coffee & espresso", "Wraps"],
        "meal_plan_accepted": False,
        "cuisine_types": ["Bagels", "Coffee", "Wraps"],
        "rating": 4.7, "tags": ["bagels", "coffee", "study-fuel", "library"],
    },
    {
        "id": "qdoba", "name": "Qdoba Mexican Eats",
        "type": "restaurant", "location": "Student Union, Ground Floor",
        "hours": "Mon–Sun 10:30 AM–9 PM",
        "menu_highlights": ["Build-your-own burrito", "Nachos", "Queso", "Vegetarian options"],
        "meal_plan_accepted": True,
        "cuisine_types": ["Mexican", "Tex-Mex"],
        "rating": 4.0, "tags": ["Mexican", "quick", "student-union", "meal-plan"],
    },
    {
        "id": "the-pit", "name": "The Pit Food Trucks",
        "type": "food_truck", "location": "The Pit, between Lenoir Hall and Undergraduate Library",
        "hours": "Mon–Fri 11 AM–2 PM (rotating trucks)",
        "menu_highlights": ["Rotating vendors", "Korean BBQ", "Jerk chicken", "Falafel wraps"],
        "meal_plan_accepted": False,
        "cuisine_types": ["Korean", "Caribbean", "Middle Eastern", "Fusion"],
        "rating": 4.4, "tags": ["food-truck", "outdoor", "variety", "lunch"],
    },
    {
        "id": "carolina-coffee", "name": "Carolina Coffee Shop",
        "type": "cafe", "location": "East Franklin Street, adjacent to campus",
        "hours": "Mon–Sat 7 AM–10 PM | Sun 8 AM–9 PM",
        "menu_highlights": ["Single-origin pour-overs", "House-baked scones", "Avocado toast", "Matcha latte"],
        "meal_plan_accepted": False,
        "cuisine_types": ["Specialty Coffee", "Brunch", "Pastries"],
        "rating": 4.8, "tags": ["specialty-coffee", "off-campus", "study-spot", "brunch"],
    },
]
